project_name: legendgraphic
builds:
  - main: ./cmd/legendgraphic/legendgraphic.go
    binary: legendgraphic
    goos:
      - windows
      - darwin
      - linux
    goarch:
      - amd64
      - 386
    ignore:
      - goos: darwin
        goarch: 386

archive:
  files:
    - template/*
    - example/*
    - LICENSE
    - README.md
